### ISSUE TITLE
how to rotate ivs player to Landscape

### ISSUE THREAD

**Issue by redevrx** [aws-samples/amazon-ivs-multiple-players-ios-demo#4]
I have to rotate its player to landscape but when orientation change it not working
` var body: some View {
   ZStack {
       if UIDevice.current.orientation.isPortrait {
           ZStack(alignment: .trailing) {
               VStack(spacing: 8, content: {
                   PlayerView(playerModel: viewModel.player1)
                           .frame(width: .infinity, height: .infinity)
               })
           }
       } else {
           ZStack {
               VStack(spacing: 8, content: {
                   PlayerView(playerModel: viewModel.player1)
                           .frame(width: .infinity, height: .infinity)
               })
           }
       }
   }.onDisappear {viewModel.pausePlayer()}}`

**Comment by slee-aws** [comment]
Hi @redevRx can you describe the issue further? Rotating the device in this demo should change the demo layout. A screen capture of the application is attached:

https://user-images.githubusercontent.com/68920478/161346267-24cec3a1-f1d7-40f1-af74-5f48548ee3d0.mp4

**Comment by slee-aws** [comment]
@redevRx - if you are looking to implement orientation changes in general, you may want to refer to a resource like this tutorial: https://www.hackingwithswift.com/quick-start/swiftui/how-to-detect-device-rotation.

Closing this issue as this does not seem like an issue related to this demo. If you are able to provide more information on how this relates to this demo, please re-open the issue or create a new issue.
